### PR TITLE
Update ToastContainer.js - related Cannot read property 'setNativeProps' of null

### PR DESCRIPTION
**Pull request by jqn**
@magicismight please merge this pull request this fixes issue https://github.com/magicismight/react-native-root-toast/issues/39 this an awesome library but if you are short on time it would be great to allow others to merge pull requests. Thanks

### CODE REVIEW

**Comment by chakrihacker** [comment]
please merge it

**Comment by taichikoumoto** [comment]
Any update on this?
I encountered this bug...

**Comment by carrawao** [comment]
Guys, this is a joke that you are not processing the open pull requests and they sit open since October 2017! Please merge!

**Comment by tannguyen208** [comment]
pls.. merge commit "~~lib/ToastContainer.js"

**Comment by MaximilienMeyer** [comment]
@magicismight Hello bro, good work on this lib but you really need to accept this MR

**Comment by magicismight** [comment]
Thanks for this PR.
Please try `react-native-root-toast@3.1.2`

**Pull request merged**
